server-name: foo-bar

# Current supported types: redis
database:
  type: redis
  hostname: localhost
  port: 6379
  username: unused-by-redis
  password: aVeryStrongPasswordToAvoidAnyBruteforceBecauseWeNowRedisIsAHighPerformanceDatabase#2017